// Generated by CoffeeScript 1.3.3
(function() {

  this.clazz = require('cardamom/lib/clazz').clazz;

  this.Fn = require('cardamom/lib/fnstuff').Fn;

  this.ErrorBase = require('cardamom/lib/errors').ErrorBase;

  this.colors = require('cardamom/lib/colors');

  this.bisect = require('cardamom/lib/bisect');

  this.collections = require('cardamom/lib/collections');

  this.hotswap = require('cardamom/lib/hotswap');

}).call(this);
