// Generated by CoffeeScript 1.3.3
(function() {
  var Set, clazz;

  clazz = require('cardamom/lib/clazz').clazz;

  this.Set = Set = clazz('Set', function() {
    return {
      init: function(elements) {
        this.elements = elements;
      }
    };
  });

}).call(this);
