// Generated by CoffeeScript 1.3.3
(function() {
  var cache, fs;

  fs = require('fs');

  cache = {};

  module.exports = function(_require, name) {
    var lastModified, resolvedName;
    resolvedName = _require.resolve(name);
    lastModified = fs.lstatSync(resolvedName).mtime;
    if (!cache[resolvedName] || lastModified > cache[resolvedName]) {
      cache[resolvedName] = lastModified;
      delete _require.cache[resolvedName];
    }
    return _require(name);
  };

}).call(this);
