{@clazz} =      require('cardamom/src/clazz')
{@Fn} =         require('cardamom/src/fnstuff')
{@ErrorBase} =  require('cardamom/src/errors')
@colors =       require('cardamom/src/colors')
@bisect =       require('cardamom/src/bisect')
@collections =  require('cardamom/src/collections')
