{@clazz} =      require('cardamom/lib/clazz')
{@Fn} =         require('cardamom/lib/fnstuff')
{@ErrorBase} =  require('cardamom/lib/errors')
@colors =       require('cardamom/lib/colors')
@bisect =       require('cardamom/lib/bisect')
@collections =  require('cardamom/lib/collections')
